"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const branch_controller_1 = require("../controllers/branch.controller");
const auth_middleware_1 = require("../Middlewares/auth.middleware");
const branchRoutes = (0, express_1.Router)();
branchRoutes.post("/create", auth_middleware_1.protect, branch_controller_1.createBranchController);
branchRoutes.put("/:branchId", auth_middleware_1.protect, branch_controller_1.updateBranchController);
branchRoutes.get("/", auth_middleware_1.protect, branch_controller_1.getMyBranchesController);
exports.default = branchRoutes;
