"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const org_routes_1 = __importDefault(require("./routes/org.routes"));
const branch_routes_1 = __importDefault(require("./routes/branch.routes"));
const zoneRoutes_1 = __importDefault(require("./routes/zoneRoutes"));
const geo_Routes_1 = __importDefault(require("./routes/geo.Routes"));
const auth_routes_1 = __importDefault(require("./routes/auth.routes"));
const user_routhes_1 = __importDefault(require("./routes/user.routhes"));
const attendance_Routes_1 = __importDefault(require("./routes/attendance.Routes"));
const app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use("/api/orgs", org_routes_1.default);
app.use("/api/branch", branch_routes_1.default);
app.use("/api/zones", zoneRoutes_1.default);
app.use("/api/geo", geo_Routes_1.default);
app.use("/api/auth", auth_routes_1.default);
app.use("/api/users", user_routhes_1.default);
app.use("api/attendance", attendance_Routes_1.default);
exports.default = app;
